import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import {Header} from '@/components/base/Header';
import { cookies } from 'next/headers';
import { AppProvider } from '@/context/AppProvider';
import { ModalProvider } from '@/context/ModalProvider';
import Footer from '@/components/base/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	//default language
	// const cookieStore = cookies();
	// const sessionToken = cookieStore.get('sessionToken')?.value || ''; 	
	return (
			<div className=''>
				{/* <header className="bg-custom-gradient border-b border-border-custom h-16 w-full fixed top-0 left-0 right-0 z-50">
					<Header />
				</header> */}
				{/* <AppProvider initialToken={sessionToken}> */}
			
					<Header />
						<div className="mt-[65px]">
							{children}
						</div>
					<Footer />
					
				{/* </AppProvider> */}
			</div>
	);
}
