import { cookies } from 'next/headers';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function LoginLayout({ children }: { children: React.ReactNode }) {
	return (
		<>
			<div>{children}</div>
		</>
	);
}
